-- ============================================================
-- SMC Performance Tracking System — Database Schema
-- Version: 1.0
-- Database: SQLite 3
-- Date: April 2, 2026
-- ============================================================

-- Enable WAL mode for better concurrent read/write performance
PRAGMA journal_mode=WAL;
PRAGMA foreign_keys=ON;

-- ============================================================
-- TABLE: signals
-- Primary table storing every signal generated by the indicator
-- ============================================================
CREATE TABLE IF NOT EXISTS signals (
    -- Primary Key
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    signal_id           TEXT UNIQUE NOT NULL,          -- Unique ID from Pine: "EURUSD_1712073600_LONG"
    
    -- Signal Identity
    pair                TEXT NOT NULL,                 -- e.g., "EURUSD", "GBPUSD"
    direction           TEXT NOT NULL CHECK(direction IN ('LONG', 'SHORT')),
    signal_type         TEXT NOT NULL DEFAULT 'STANDARD' CHECK(signal_type IN ('STANDARD', 'COUNTER_TREND')),
    
    -- Prices
    entry_price         REAL NOT NULL,                 -- Price at signal generation
    stop_loss           REAL NOT NULL,                 -- Calculated SL price
    take_profit         REAL NOT NULL,                 -- Calculated TP price (at target R:R)
    sl_distance_pips    REAL,                          -- SL distance in pips
    tp_distance_pips    REAL,                          -- TP distance in pips
    
    -- HUD Snapshot at Signal Time
    structure           TEXT,                          -- 'BULLISH' or 'BEARISH'
    h4_bias             TEXT,                          -- 'BULLISH' or 'BEARISH'
    zone                TEXT,                          -- 'PREMIUM', 'DISCOUNT', 'EQUILIBRIUM'
    poi_status          TEXT,                          -- 'IN POI', 'No POI'
    liquidity           TEXT,                          -- 'SWEPT', 'Not Swept'
    poi_score           INTEGER CHECK(poi_score BETWEEN 0 AND 7),  -- POI score (0-7 with bonuses)
    m15_status          TEXT,                          -- 'Sweep Confirmed', 'Waiting', 'In OB Zone'
    m5_status           TEXT,                          -- 'Entry Confirmed', 'Waiting for M15'
    reversal_risk       TEXT,                          -- 'Low', 'Medium', 'High'
    kill_zone           TEXT,                          -- 'London KZ', 'NY AM KZ', 'NY PM KZ', 'Asian KZ', 'Outside KZ'
    kill_zone_id        INTEGER DEFAULT 0,             -- 0=Outside, 1=London, 2=NY AM, 3=NY PM, 4=Asian
    pattern             TEXT,                          -- 'Double Top', 'Double Bottom', 'H&S', 'Inv H&S', 'Clear'
    pattern_aligned     INTEGER DEFAULT 0,             -- 1=pattern supports direction, 0=neutral, -1=conflicts
    amd_phase           TEXT,                          -- 'ACCUMULATION', 'MANIPULATION', 'DISTRIBUTION', 'TRANSITION'
    amd_phase_id        INTEGER DEFAULT 0,             -- 0=Off, 1=Accum, 2=Manip, 3=Dist, 4=Trans
    entry_model         TEXT,                          -- 'Disp. Trap', 'Refined OB', 'Breaker Blk', 'Flip Zone', 'Confluence'
    entry_model_id      INTEGER DEFAULT 0,             -- 1=DT, 2=ROB, 3=BB, 4=FZ, 5=CE
    target_rr           REAL DEFAULT 3.0,              -- Target R:R ratio
    workflow_step       TEXT,                          -- Workflow state at signal time
    
    -- Fibonacci Data
    fib_zone            TEXT,                          -- 'Fib 61.8%', 'Fib 78.6%', 'Fib 88.6%', 'Fib 90%+ EXTREME'
    fib_zone_id         INTEGER DEFAULT 0,             -- 0=none, 618=61.8%, 786=78.6%, 886=88.6%, 900=90%+
    fib_poi_bonus       REAL DEFAULT 0.0,              -- POI bonus from Fib zone (0, 0.5, 1.0, 1.5, 2.0)
    
    -- Timestamps
    signal_timestamp    TEXT NOT NULL,                 -- ISO 8601 from TradingView bar time
    server_timestamp    TEXT NOT NULL DEFAULT (datetime('now')),  -- When server received it
    
    -- Timezone & Session Data
    signal_hour_utc     INTEGER,                       -- Hour (0-23) in UTC
    signal_hour_est     INTEGER,                       -- Hour (0-23) in EST/EDT
    signal_day_of_week  INTEGER,                       -- 0=Monday, 6=Sunday
    session             TEXT,                          -- 'London', 'New York', 'Asian', 'Overlap'
    
    -- Outcome Tracking
    status              TEXT NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE', 'WON', 'LOST', 'TIMEOUT', 'GET_OUT', 'CANCELLED')),
    outcome_timestamp   TEXT,                          -- When TP/SL/Timeout occurred
    outcome_price       REAL,                          -- Price when outcome determined
    bars_to_outcome     INTEGER,                       -- Number of bars from entry to outcome
    time_to_outcome_min INTEGER,                       -- Minutes from entry to outcome
    
    -- Maximum Favorable/Adverse Excursion
    mfe_price           REAL,                          -- Best price reached in signal direction
    mfe_pips            REAL,                          -- MFE in pips
    mfe_rr              REAL,                          -- MFE as R:R multiple
    mae_price           REAL,                          -- Worst price reached against signal
    mae_pips            REAL,                          -- MAE in pips
    mae_rr              REAL,                          -- MAE as R:R multiple
    
    -- Actual R:R Achieved
    actual_rr           REAL,                          -- Actual R:R at outcome (negative for losses)
    pips_gained         REAL,                          -- Net pips (positive or negative)
    
    -- Price at various intervals (for movement analysis)
    price_5m_after      REAL,                          -- Price 5 minutes after signal
    price_15m_after     REAL,                          -- Price 15 minutes after signal
    price_1h_after      REAL,                          -- Price 1 hour after signal
    price_4h_after      REAL,                          -- Price 4 hours after signal
    
    -- Manual Trade Tracking
    trade_status        TEXT DEFAULT 'pending' CHECK(trade_status IN ('pending', 'taken', 'missed', 'ignored')),
    actual_entry_price  REAL,                          -- Actual price trader entered at
    actual_exit_price   REAL,                          -- Actual price trader exited at
    actual_entry_time   TEXT,                          -- When trader actually entered
    actual_exit_time    TEXT,                          -- When trader actually exited
    actual_pnl          REAL,                          -- Actual P&L in pips
    trade_notes         TEXT,                          -- Notes about the trade decision
    
    -- Metadata
    indicator_version   TEXT DEFAULT 'v13.4',          -- Indicator version
    timeframe           TEXT DEFAULT '15m',            -- Chart timeframe
    notes               TEXT,                          -- Optional notes
    
    -- Indexes support
    created_at          TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at          TEXT NOT NULL DEFAULT (datetime('now'))
);

-- ============================================================
-- TABLE: price_ticks
-- Stores price snapshots for active signal tracking
-- ============================================================
CREATE TABLE IF NOT EXISTS price_ticks (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    signal_id           TEXT NOT NULL,                 -- FK to signals.signal_id
    pair                TEXT NOT NULL,
    timestamp           TEXT NOT NULL DEFAULT (datetime('now')),
    bid_price           REAL,
    ask_price           REAL,
    mid_price           REAL NOT NULL,                 -- (bid+ask)/2 or last price
    is_mfe_update       INTEGER DEFAULT 0,             -- 1 if this tick updated MFE
    is_mae_update       INTEGER DEFAULT 0,             -- 1 if this tick updated MAE
    
    FOREIGN KEY (signal_id) REFERENCES signals(signal_id) ON DELETE CASCADE
);

-- ============================================================
-- TABLE: signal_events
-- Stores lifecycle events for each signal
-- ============================================================
CREATE TABLE IF NOT EXISTS signal_events (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    signal_id           TEXT NOT NULL,
    event_type          TEXT NOT NULL CHECK(event_type IN (
        'ENTRY', 'TP_HIT', 'SL_HIT', 'TIMEOUT', 'GET_OUT',
        'UPDATE', 'PRICE_UPDATE', 'MFE_UPDATE', 'MAE_UPDATE',
        'CANCELLED'
    )),
    event_timestamp     TEXT NOT NULL DEFAULT (datetime('now')),
    event_data          TEXT,                          -- JSON blob with event-specific data
    price_at_event      REAL,
    
    FOREIGN KEY (signal_id) REFERENCES signals(signal_id) ON DELETE CASCADE
);

-- ============================================================
-- TABLE: daily_metrics
-- Pre-computed daily aggregates for fast dashboard loading
-- ============================================================
CREATE TABLE IF NOT EXISTS daily_metrics (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    date                TEXT NOT NULL,                 -- YYYY-MM-DD
    pair                TEXT NOT NULL,                 -- Pair or 'ALL' for aggregate
    
    total_signals       INTEGER DEFAULT 0,
    wins                INTEGER DEFAULT 0,
    losses              INTEGER DEFAULT 0,
    timeouts            INTEGER DEFAULT 0,
    get_outs            INTEGER DEFAULT 0,
    
    win_rate            REAL DEFAULT 0.0,              -- wins / (wins + losses)
    avg_rr_achieved     REAL DEFAULT 0.0,
    avg_pips_won        REAL DEFAULT 0.0,
    avg_pips_lost       REAL DEFAULT 0.0,
    expectancy          REAL DEFAULT 0.0,              -- (winRate * avgWin) - (lossRate * avgLoss)
    profit_factor       REAL DEFAULT 0.0,              -- gross_profit / gross_loss
    
    -- Breakdowns (stored as JSON for flexibility)
    by_poi_score        TEXT,                          -- JSON: {"5/5": {"wins": 10, "total": 12}, ...}
    by_entry_model      TEXT,                          -- JSON: {"Disp. Trap": {"wins": 5, "total": 20}, ...}
    by_kill_zone        TEXT,                          -- JSON: {"London KZ": {"wins": 8, "total": 15}, ...}
    by_amd_phase        TEXT,                          -- JSON
    by_pattern          TEXT,                          -- JSON
    
    computed_at         TEXT NOT NULL DEFAULT (datetime('now')),
    
    UNIQUE(date, pair)
);

-- ============================================================
-- TABLE: pair_config
-- Configuration for each tracked pair
-- ============================================================
CREATE TABLE IF NOT EXISTS pair_config (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    pair                TEXT UNIQUE NOT NULL,
    pip_size            REAL NOT NULL,                 -- 0.0001 for most FX, 0.01 for JPY pairs
    display_name        TEXT,                          -- "EUR/USD"
    is_active           INTEGER DEFAULT 1,
    created_at          TEXT NOT NULL DEFAULT (datetime('now'))
);

-- ============================================================
-- TABLE: system_log
-- Application-level event logging
-- ============================================================
CREATE TABLE IF NOT EXISTS system_log (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp           TEXT NOT NULL DEFAULT (datetime('now')),
    level               TEXT NOT NULL CHECK(level IN ('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL')),
    component           TEXT NOT NULL,                 -- 'webhook', 'tracker', 'analytics', 'dashboard'
    message             TEXT NOT NULL,
    details             TEXT                           -- JSON blob for extra context
);

-- ============================================================
-- INDEXES
-- ============================================================

-- Signals: Most common query patterns
CREATE INDEX IF NOT EXISTS idx_signals_pair ON signals(pair);
CREATE INDEX IF NOT EXISTS idx_signals_status ON signals(status);
CREATE INDEX IF NOT EXISTS idx_signals_direction ON signals(direction);
CREATE INDEX IF NOT EXISTS idx_signals_signal_timestamp ON signals(signal_timestamp);
CREATE INDEX IF NOT EXISTS idx_signals_pair_status ON signals(pair, status);
CREATE INDEX IF NOT EXISTS idx_signals_poi_score ON signals(poi_score);
CREATE INDEX IF NOT EXISTS idx_signals_entry_model_id ON signals(entry_model_id);
CREATE INDEX IF NOT EXISTS idx_signals_kill_zone_id ON signals(kill_zone_id);
CREATE INDEX IF NOT EXISTS idx_signals_amd_phase_id ON signals(amd_phase_id);
CREATE INDEX IF NOT EXISTS idx_signals_created_at ON signals(created_at);
CREATE INDEX IF NOT EXISTS idx_signals_trade_status ON signals(trade_status);

-- Price ticks: Query by signal
CREATE INDEX IF NOT EXISTS idx_price_ticks_signal_id ON price_ticks(signal_id);
CREATE INDEX IF NOT EXISTS idx_price_ticks_timestamp ON price_ticks(timestamp);

-- Signal events: Query by signal and type
CREATE INDEX IF NOT EXISTS idx_signal_events_signal_id ON signal_events(signal_id);
CREATE INDEX IF NOT EXISTS idx_signal_events_type ON signal_events(event_type);

-- Daily metrics: Query by date and pair
CREATE INDEX IF NOT EXISTS idx_daily_metrics_date ON daily_metrics(date);
CREATE INDEX IF NOT EXISTS idx_daily_metrics_pair ON daily_metrics(pair);

-- ============================================================
-- SEED DATA: Default pair configurations
-- ============================================================
INSERT OR IGNORE INTO pair_config (pair, pip_size, display_name) VALUES
    ('EURUSD', 0.0001, 'EUR/USD'),
    ('GBPUSD', 0.0001, 'GBP/USD'),
    ('USDJPY', 0.01,   'USD/JPY'),
    ('AUDUSD', 0.0001, 'AUD/USD'),
    ('USDCAD', 0.0001, 'USD/CAD'),
    ('NZDUSD', 0.0001, 'NZD/USD'),
    ('USDCHF', 0.0001, 'USD/CHF'),
    ('GBPJPY', 0.01,   'GBP/JPY'),
    ('EURJPY', 0.01,   'EUR/JPY'),
    ('XAUUSD', 0.01,   'XAU/USD'),
    ('BTCUSD', 0.01,   'BTC/USD');

-- ============================================================
-- TRIGGERS
-- ============================================================

-- Auto-update updated_at on signals table
CREATE TRIGGER IF NOT EXISTS trg_signals_updated_at
    AFTER UPDATE ON signals
    FOR EACH ROW
BEGIN
    UPDATE signals SET updated_at = datetime('now') WHERE id = OLD.id;
END;
